# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Prepare Host
      run: |
        sudo apt-get -qq update || true
        sudo apt-get install -y conntrack
        # install minikube
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mkdir -p /usr/local/bin/
        sudo install minikube /usr/local/bin/
        minikube version
        ls -la

    - name: Create PSP enabled Cluster
      run: |
        sudo ./hack/kubernetes/create-psp-cluster.sh
        ls -l /var/lib/minikube/kubeconfig
        cat /var/lib/minikube/kubeconfig
        sudo ls -l $HOME/.kube
        sudo chown -R $USER $HOME/.kube $HOME/.minikube
        cat $HOME/.kube/config
        kubectl version --short

    - name: Test local storage
      run: |
        kubectl apply -f ./hack/kubernetes/pod.yaml
        kubectl get pods
        sleep 5
        kubectl get pods
        sleep 5
        kubectl get pods
        sleep 5
